---
title: "loop"
author: "T"
date: "`r Sys.Data()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# if else

##basic
if (conditon){
   do something
} else{
   do something
}

## more

if (conditon){
   do something
} else if (conditon){
   do something different
} else {
   do something different
}

```{r}
#Ex.1

if (x>5){
         y<-1 #TRUE
} else{
       y<-0   #FALSE
}

```

#if 

if (condition1){

}

if (condition2){

}

#for

for(var in seq) statment\

nomally: for (i in x) ----- i is index of x

loop statment until condtion FALSE\

```{r}
#EX.1
for (i in 1:10) {
  print(i)
}

#EX.2 --- all same 

x <- c("a","b","c","d")

for(i in 1:4){
  print(x[i])
}

for(i in seq_along(x)){
  print(x[1])
}

```

## for ---nested
```{r}

x<- matrix(1:6,2,3)
x


for(i in seq_len(nrow(x))){          #loop i first
  for(j in seq_len(ncol(x))){        #then loop j
      print(x[i,j])   #like (1,1), (1,2), (1,3), (2,1),(2,2),(2,3)  
  }
}

```


#while


```{r}

```

