---
title: "Untitled"
author: "T"
date: "January 21, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#1. setequal vs identical

```{r}
a <- rep(1:3, 1:3)
b <- 1:3
setequal(a, b)  # TRUE
identical(a, b)  # FALSE
```

#2. cbind vs rbind

cbind by column , column need same

```{r}

a <- matrix(1:12, 3, 4)
b <- matrix(-1:-12, 3, 4))

x=cbind(a,b)
```
rbind by row , row need same

```{r}
y=rbind(a,b)
```
#3. model.frame

model.frame(bm1$glm_CA)

#4 intersect

```{r}
a <- c(1,2)
b <- c(1.3)
intersect(a, b)
```
#5 setNames

```{r}
comm <- setNames(nm=intersect(a$col, b$col))
```

#6 pull


```{r}
data("mtcars")
head(mtcars)

mtcars %>% pull(cyl)
```
#7 exact2 =[[]]


#8 map

```{r}
mtcars %>% map(sum)

mtcars %>% map_dbl(sum)
```

#9 NA


```{r}
df <- tibble(x = c(1, 2, NA), y = c("a", NA, "b"), z = list(1:5, NULL, 10:20))
df %>% replace_na(list(x = 0, y = "unknown"))

df %>% mutate(x = replace_na(x, 0))
```

#10

```{r}
mtcars %>%
  split(.$cyl) %>%
  map(~ lm(mpg ~ wt, data = .))


l.ex <- list(a = list(1:5, LETTERS[1:5]), b = "Z", c = NA)
unlist(l.ex, recursive = FALSE)
unlist(l.ex, recursive = TRUE)



mtcars %>% pull(1)
mtcars %>% pull(cyl)
mtcars[[1]]


library(purrr)

numbers <- list(11, 12, 13, 14)

possible_sqrt <- possibly(sqrt, otherwise = NA_real_)

numbers_with_error <- list(1, 2, 3, "spam", 4)

map(numbers_with_error, possible_sqrt)


lmfit <- lm(mpg ~ wt, mtcars)
lmfit

summary(lmfit)

library(broom)
tidy(lmfit)
augment(lmfit)
lmfit$terms

```

