---
title: "Standardized workflow for rmarkdown "
author: "T"
date: "`r Sys.Date()`"
output: html_document
---


#Setup knitr
```{r setup, collapse=TRUE, cache=FALSE, echo = FALSE, results="hide", message = FALSE}
# this chunk setup options for knitr 
suppressPackageStartupMessages(require(knitr))
suppressPackageStartupMessages(require(rprojroot))

root.dir <- rprojroot::find_rstudio_root_file()
root.dir #point out working dir

knitr::opts_knit$set(root.dir = root.dir) # all paths in code chunks are relative to this root.dir

#once the root.dir change the paths and code change

#nice way to change working directory

knitr::opts_chunk$set(comment = "",  cache=FALSE, message = FALSE, echo = TRUE, tidy = FALSE, collapse=TRUE)
options(width = 288)
```



```{r setup directory}
# this chunk setup directory and load functions
options(stringsAsFactors = FALSE)
data.dir <- file.path(root.dir, "rdata") #combine to a new directory path
html.dir <- file.path(root.dir, "html")
graph.dir <- file.path(root.dir,"graph")
```

Load library

```{r}
install.packages("tidyverse")
library(tidyverse)
library(ggplot2)
library(magrittr)
install.packages("diagram")
library(diagram)

```



```{r}
diamonds <- ggplot2::diamonds
diamonds2 <- diamonds %>%
dplyr::mutate(price_per_carat = price / carat)
```


# %T>%
```{r}
library(diagram)


```





